# Generated by Django 4.1.7 on 2023-04-07 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='data',
        ),
    ]
