# Generated by Django 4.1.7 on 2023-03-31 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_type_alter_transaction_reciever_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='reciever',
            new_name='recipient',
        ),
    ]
