# Generated by Django 4.1.7 on 2023-04-19 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_alter_transaction_amount_alter_transaction_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='source',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
    ]
