# Generated by Django 4.1.7 on 2023-03-20 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('currency', models.CharField(choices=[('GBP', 'British Pound'), ('USD', 'United States Dollar'), ('EUR', 'Euro')], default='USD', max_length=5)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('base_currency', models.CharField(choices=[('GBP', 'British Pound'), ('USD', 'United States Dollar'), ('EUR', 'Euro')], default='USD', max_length=5)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('DECLINED', 'Declined'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_reciever', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(choices=[('GBP', 'British Pound'), ('USD', 'United States Dollar'), ('EUR', 'Euro')], default='USD', max_length=5)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('MONREQ', 'Money Request'), ('MONREC', 'Money Recieved'), ('TRANSUC', 'Transaction Success'), ('TRANPEN', 'Transaction Pending'), ('TRANDEC', 'Transaction Declined'), ('ACCVER', 'Account Verified'), ('ACCSUS', 'Account Suspended'), ('INFO', 'Information')], default='INFO', max_length=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
