# Generated by Django 4.1.7 on 2023-04-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallet_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=1000, max_digits=10),
        ),
    ]
